//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asgla.Explosion.Request {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Requests : global::System.Configuration.ApplicationSettingsBase {
        
        private static Requests defaultInstance = ((Requests)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Requests())));
        
        public static Requests Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.Login")]
        public string Login {
            get {
                return ((string)(this["Login"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.Chat")]
        public string Chat {
            get {
                return ((string)(this["Chat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.EquipItem")]
        public string EquipItem {
            get {
                return ((string)(this["EquipItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.Ping")]
        public string Ping {
            get {
                return ((string)(this["Ping"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.Game")]
        public string Game {
            get {
                return ((string)(this["Game"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.Join")]
        public string Join {
            get {
                return ((string)(this["Join"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.JoinFirst")]
        public string JoinFirst {
            get {
                return ((string)(this["JoinFirst"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.MoveToArea")]
        public string MoveToArea {
            get {
                return ((string)(this["MoveToArea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.PlayerLoadData")]
        public string PlayerData {
            get {
                return ((string)(this["PlayerData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.PlayerLoadInventory")]
        public string PlayerInventory {
            get {
                return ((string)(this["PlayerInventory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asgla.Explosion.Request.Asgla.Default")]
        public string None {
            get {
                return ((string)(this["None"]));
            }
        }
    }
}
